spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/code_challenge
    username: root
    password: 123456
  # Redis 配置
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      timeout: 5000